#根据不同版本使用mysql.driver
mysql.drvier=com.mysql.jdbc.Driver
#mysql.drvier=com.mysql.cj.jdbc.Driver
#记得改表名、账号、密码
mysql.url=jdbc:mysql://localhost:3306/study_todolist?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
mysql.user=root
mysql.pwd=123456

#以下写法也行
##drvier=com.mysql.jdbc.Driver
#drvier=com.mysql.cj.jdbc.Driver
#url=jdbc:mysql://localhost:3306/study_fruits?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#user=root
#pwd=123456